check is now working

diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -38,6 +38,9 @@ configure_credentials "$payload"
 
 skip_ssl_verification=$(jq -r '.source.skip_ssl_verification // false' < ${payload})
 uri=$(jq -r '.source.uri // ""' < "$payload")
+uri_schema=$(jq -r '.source.uri_schema // ""' < "$payload")
+uri_address=$(jq -r '.source.uri_address // ""' < "$payload")
+repo_project=$(jq -r '.source.repo_project // ""' < "$payload")
 git_config_payload=$(jq -r '.source.git_config // []' < "$payload")
 rebuild_when_target_changed=$(jq -r '.source.rebuild_when_target_changed // "false"' < "$payload")
 rebuild_phrase=$(jq -r '.source.rebuild_phrase // "test this please"' < "$payload")
@@ -63,6 +66,21 @@ fi
 
 if [ -z "$status" ]; then
   log "invalid payload (missing status)"
+  exit 1
+fi
+
+if [ -z "$uri_address" ]; then
+  log "invalid payload (missing uri_address):" "$(cat $payload)"
+  exit 1
+fi
+
+if [ -z "$uri_schema" ]; then
+  log "invalid payload (missing uri_schema):" "$(cat $payload)"
+  exit 1
+fi
+
+if [ -z "$repo_project" ]; then
+  log "invalid payload (missing repo_project):" "$(cat $payload)"
   exit 1
 fi
 
@@ -129,7 +147,6 @@ target_commit=$(git rev-list --parents -1 $merge_commit | awk '{print $2}')
 
 # determine repository name for calling REST api
 repo_name=$(basename "$uri" | sed "s/.git$//")
-repo_project=$(basename $(dirname "$uri"))
 
 # parse uri and retrieve host
 uri_parser "$uri"
